version: "3.7"
services:
  postgres:
    build: ../postgres/
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ../postgres/volume/data:/var/lib/postgresql/data

  graphile:
    # container_name: pgql
    restart: always
    build: ./
    depends_on:
      - postgres
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command:
      [
        "--connection",
        "postgres://postgres:secret@postgres:5432/postgres",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--schema",
        "api",
        "--watch",
      ]
    # links:
    #   - postgres
    # networks:
    #   - psql-pgql
# networks:
#   psql-pgql:
